### ISSUE TITLE
VP Promotion Text Update (> v2.3.1)

### ISSUE THREAD

**Issue by LessRekkless** [adaneslavo/Promotion-Overhaul-for-VP#5]
Updates to base VP text for the version after 2.3.1.

Text I think you should pay attention to:
- Promotion Text Additions:
    TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP  (added to PROMOTION_ANTI_SUBMARINE_I, clarifies that it is both CS on attack and general CS),
    TXT_KEY_PROMOTION_ANTI_SUBMARINE_II_HELP (added to PROMOTION_ANTI_SUBMARINE_II, clarifies that it is both CS on attack and general CS),
    TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP (added to PROMOTION_ANTI_HELICOPTER),
    TXT_KEY_PROMOTION_HEAVY_PAYLOAD_HELP (added to PROMOTION_HEAVY_PAYLOAD),
    TXT_KEY_PROMOTION_MORALE_EVENT (added to PROMOTION_MORALE_EVENT);
 - Text Changes (clarify that promotions are based on health percentages) :
    TXT_KEY_EUPANEL_BONUS_VS_MORE_50_HP_UNITS,
    TXT_KEY_EUPANEL_BONUS_VS_LESS_50_HP_UNITS,
    TXT_KEY_PROMOTION_ACCURACY_1_HELP,
    TXT_KEY_PROMOTION_ACCURACY_2_HELP,
    TXT_KEY_PROMOTION_ACCURACY_3_HELP,
    TXT_KEY_PROMOTION_ACCURACY_4_HELP,
    TXT_KEY_PROMOTION_BARRAGE_1_HELP,
    TXT_KEY_PROMOTION_BARRAGE_2_HELP,
    TXT_KEY_PROMOTION_BARRAGE_3_HELP,
    TXT_KEY_PROMOTION_PRIZE_RULES_HELP,
    TXT_KEY_PROMOTION_SKIRMISHER_POWER_HELP,
    TXT_KEY_PROMOTION_TARGETING_1_HELP,
    TXT_KEY_PROMOTION_TARGETING_2_HELP,
    TXT_KEY_PROMOTION_TARGETING_3_HELP,
    TXT_KEY_PROMOTION_TERROR_HELP,
    TXT_KEY_PROMOTION_TERROR_II_HELP;
 - Other Text Fixes :
    TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP, (now used for both AIR_AMBUSH_1 and AIR_AMBUSH_2
    TXT_KEY_PROMOTION_AIR_AMBUSH_2_HELP, (no longer used)
    TXT_KEY_PROMOTION_ANTI_AIR_HELP (clarify that it works against gunships),
    TXT_KEY_PROMOTION_ANTI_AIR_II_HELP (clarify that it works against gunships),
    TXT_KEY_PROMOTION_BARRAGE_4_HELP (clarifies that it works with Combat Strength not just ranged),
    TXT_KEY_PROMOTION_ENEMY_BLADE_HELP (clarifies that the heal happens at the beginning of turn),
    TXT_KEY_PROMOTION_SKI_INFANTRY_HELP (clarifies that it works for general Combat Strength (only in bare snow/tundra/hills)),

Here is the entire commit:
https://github.com/LoneGazebo/Community-Patch-DLL/pull/8843/commits/59ca79f2702591eb804a1b6f62cae8f56fb82d39

**Comment by adaneslavo** [comment]
Almost done.
Couldn't find
TXT_KEY_EUPANEL_BONUS_VS_MORE_50_HP_UNITS,
TXT_KEY_EUPANEL_BONUS_VS_LESS_50_HP_UNITS,
