### ISSUE TITLE
Incorrect / Out-of-Date Promotion Text

### ISSUE THREAD

**Issue by LessRekkless** [adaneslavo/Promotion-Overhaul-for-VP#6]
- TXT_KEY_PROMOTION_CITY_SIEGE is incorrect, it should be 33% for both effects, not 50%.
- TXT_KEY_PROMOTION_SKI_INFANTRY is incomplete, combat bonus does not include forested terrain.

**Comment by adaneslavo** [comment]
First gives +100% now and it's the same database shows.
Second corrected.
Sorry for the delay :P
