### ISSUE TITLE
VP Promotion Text Update (v2.6) 

### ISSUE THREAD

**Issue by LessRekkless** [adaneslavo/Promotion-Overhaul-for-VP#7]
Updates to base VP text for the version after 2.6.

Text I think you should pay attention to:

- Promotion Text Additions
   TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP
   TXT_KEY_PROMOTION_OCEAN_HALF_MOVES
   TXT_KEY_PROMOTION_OCEAN_HALF_MOVES_HELP
   TXT_KEY_PROMOTION_ASSIZE_OF_ARMS
   TXT_KEY_PROMOTION_ASSIZE_OF_ARMS_HELP
   TXT_KEY_PROMOTION_SCOUT_CAVALRY
   TXT_KEY_PROMOTION_SCOUT_CAVALRY_HELP
   TXT_KEY_PROMOTION_FIELD_WORKS_0
   TXT_KEY_PROMOTION_FIELD_WORKS_0_HELP

All other text is standardization, no clarifications.

Here is the entire commit:
https://github.com/LoneGazebo/Community-Patch-DLL/commit/d5652f493fe0beea9140203dedcd1505ba1265ca

**Comment by adaneslavo** [comment]
Done.
